### ISSUE TITLE
normalize whitakter's 5th, 6th, 7th, 8th conjugation to 'irregular'

### ISSUE THREAD

**Issue by balmas** [alpheios-project/morph-client#15]
reported by @monzug 

The majority of latin grammars have 4 conjugations + irregular verbs, and so does Alpheios in the inflected tables and the Bennett grammar. I could not find much information about the use and meaning of the extra 3 conjugations (is there also an 8th conjugation?), so I am assuming that verbs of the 5th, 6th and 7th conjugation are irregular, some of them very common (e.g.sum, possum).
In the case of sum, Alpheios says that it belongs to the 5th conjugation, but the related inflected table is the verb-irregular. Do we need to mention the 5th, 6th or 7th conjugation? if we do, would it be better to add irregular before the 5th, 6th or 7th conjugation? Right now, it's confusing as I am expecting to have a 5th or 6th or 7th conjugation inflected table.

Per email discussion, we should normalize these and represent as 'irregular'

**Comment by balmas** [comment]
more from @monzug 

See below the output from Whitaker for 5th, 6th and 7th conjugation. these are all irregular verbs.

inqu.am              V      7 2 PRES ACTIVE  IND 1 S   
inquiam, -, -  V   [XXXAX] 
say (defective); (postpositive - for direct quote); [inquiens -> saying];


poss.um              V      5 2 PRES ACTIVE  IND 1 S   
possum, posse, potui, -  V   [XXXAX] 
be able, can; [multum  posse => have much/more/most influence/power];

vol.o                V      6 2 PRES ACTIVE  IND 1 S   
volo, velle, volui, -  V   [XXXAX] 
wish, want, prefer; be willing, will;
vol.o                V      1 1 PRES ACTIVE  IND 1 S   
volo, volare, volavi, volatus  V   [XXXAX] 
fly;
volo                 N      3 1 NOM S M                
volo                 N      3 1 VOC S M                
volo, volonis  N  M   [XWXDC]    lesser
volunteers (pl.); (in the Second Punic War);

I found some information about the existing of a 5th conjugation with an i in the stem, but the traditional grammars consider these verbs as exception of the 3rd conjugation or so called third-io conjugation. These are verbs like capere, cupere, fugere, a mix of 3rd and 4th conjugation only in the present. Interesting enough, the Whitaker assigned these verbs to the 3rd conjugation.

fugi.o               V      3 1 PRES ACTIVE  IND 1 S   
fugio, fugere, fugi, fugitus  V   [XXXAX] 
flee, fly, run away; avoid, shun; go into exile;

At this point, I think it is ok to say that 5th, 6th and 7th conjugation are irregular verbs.

**Comment by balmas** [comment]
another test case: amassi reports the 8th conjugation

**Comment by balmas** [comment]
@monzug you can test this with the build in https://github.com/alpheios-project/webextension/tree/issues-whitakers-engine

**Comment by monzug** [comment]
we do not have the 5th, 6th , 7th and 8th conjugation anymore, just verb irregular. however, we do not have the verb irregular available in the verb dropdown for some verbs, such as absum,
malo, nolo, inquam  - is this because we do not have the irregular table for these verbs?
same question as per #166.

**Comment by balmas** [comment]
correct, we currently only have irregular verb tables for these Latin lemmas:

sum, fero, volo, eo, possum

This is being discussed via https://github.com/alpheios-project/inflection-tables/issues/70
