### ISSUE TITLE
constructing headword from stem should not require suffix

### ISSUE THREAD

**Issue by balmas** [alpheios-project/morph-client#18]
when an entry doesn't have a hdwd, we construct it from the stem and suffix of the first inflection. But in some cases, such as for 'ego' we don't have a suffix. This line causes a crash:

```
lexeme.rest.entry.dict.hdwd.$ = inflectionsJSON[0].term.stem.$ + inflectionsJSON[0].term.suff.$
```

**Comment by balmas** [comment]
@monzug you can test this with the build in https://github.com/alpheios-project/webextension/tree/issues-whitakers-engine

I don't currently know of any other test cases than 'ego' but I'm sure there are some...

**Comment by balmas** [comment]
@monzug this can now be tested in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-3

**Comment by monzug** [comment]
tested using ego, tu, nobis, quid, quis, osti  -> works fine in Firefox and Chrome
